"""
Demand Forecasting Agent
==========================
Wraps the trained demand_model.pkl to produce per-product demand forecasts,
along with a plain-language summary of the trend (rising/falling/stable).

NOTE ON LLM USAGE: in the final system, the natural-language summary below
would be generated by calling Groq/Ollama with the computed numbers as
context (e.g. "Product X: predicted 45 units next week, up 20% from last
week -- write a one-sentence summary for a business owner"). For now, this
uses a simple template-based summary so the agent is fully testable without
needing API keys set up yet. Swapping the template for a real LLM call
later is a small, isolated change (see generate_summary() below).
"""

import sqlite3
import pandas as pd
import joblib
import json
from datetime import datetime
import sys
import os

sys.path.append(os.path.dirname(__file__))
from demand_utils import predict_next_day_demand, build_feature_row

DB_PATH = "data/ecommerce.db"
MODEL_PATH = "models/demand_model.pkl"
FEATURES_PATH = "models/demand_model_features.txt"


def load_model():
    model = joblib.load(MODEL_PATH)
    with open(FEATURES_PATH) as f:
        feature_cols = f.read().splitlines()
    return model, feature_cols


def log_action(conn, action, details):
    conn.execute(
        "INSERT INTO agent_logs (timestamp, agent_name, action, details) VALUES (?, ?, ?, ?)",
        (datetime.now().isoformat(), "Demand Forecasting", action, json.dumps(details)),
    )
    conn.commit()


def get_recent_average(conn, product_id, days=7):
    """Recent actual average, used to compare against the new prediction (trend direction)."""
    history = pd.read_sql(
        """SELECT units_sold FROM sales_history
           WHERE product_id = ? ORDER BY sale_date DESC LIMIT ?""",
        conn, params=(product_id, days),
    )
    if history.empty:
        return None
    return history["units_sold"].mean()


def generate_summary(product_name, predicted_daily, recent_avg):
    """
    Template-based summary for now -- structured to be swapped for a real
    LLM call later without changing anything else in this agent.
    """
    if recent_avg is None or recent_avg == 0:
        return f"{product_name}: predicted demand of {predicted_daily:.1f} units/day (no recent history to compare trend)."

    change_pct = ((predicted_daily - recent_avg) / recent_avg) * 100

    if change_pct > 15:
        trend_word = f"rising (+{change_pct:.0f}% vs last 7 days)"
    elif change_pct < -15:
        trend_word = f"falling ({change_pct:.0f}% vs last 7 days)"
    else:
        trend_word = "stable, in line with recent sales"

    return f"{product_name}: predicted {predicted_daily:.1f} units/day next week, demand {trend_word}."


def forecast_all_products(conn, model, feature_cols):
    """
    Returns a list of forecast dicts, one per product with enough history.
    This is the function the Streamlit dashboard and Inventory Agent's
    upstream logic will call.
    """
    products = pd.read_sql("SELECT product_id, name, category FROM products", conn)
    results = []

    for _, product in products.iterrows():
        pid = int(product["product_id"])
        predicted_daily = predict_next_day_demand(conn, pid, model, feature_cols)

        if predicted_daily is None:
            continue

        recent_avg = get_recent_average(conn, pid)
        predicted_weekly = predicted_daily * 7  # simplified weekly estimate, see demand_utils.py note

        summary = generate_summary(product["name"], predicted_daily, recent_avg)

        results.append({
            "product_id": pid,
            "name": product["name"],
            "category": product["category"],
            "predicted_daily_demand": round(predicted_daily, 1),
            "predicted_weekly_demand": round(predicted_weekly, 1),
            "recent_7day_avg": round(recent_avg, 1) if recent_avg is not None else None,
            "summary": summary,
        })

    return results


if __name__ == "__main__":
    conn = sqlite3.connect(DB_PATH)
    model, feature_cols = load_model()

    print("Running Demand Forecasting Agent...\n")
    results = forecast_all_products(conn, model, feature_cols)

    print(f"Generated forecasts for {len(results)} products\n")
    print("--- Sample forecasts ---")
    for r in results[:10]:
        print(f"  {r['summary']}")

    rising = [r for r in results if "rising" in r["summary"]]
    falling = [r for r in results if "falling" in r["summary"]]
    print(f"\nProducts trending up: {len(rising)}")
    print(f"Products trending down: {len(falling)}")

    log_action(conn, "forecast_completed", {
        "total_forecasted": len(results),
        "rising_count": len(rising),
        "falling_count": len(falling),
    })

    conn.close()